### ISSUE TITLE
Durable Entities support?

### ISSUE THREAD

**Issue by mtaron** [microsoft/durabletask-dotnet#116]
Congrats on 1.0!

The readme calls out some missing features:
> There are also several features that aren't yet available:
    - Durable Entities is not yet supported.
    - APIs for calling HTTP endpoints are not yet available.
    - Several instance management APIs are not yet implemented.

Are these still missing in 1.0? Or is the documentation perhaps out of date?

**Comment by jviau** [comment]
These are still missing in 1.0. We are working on implementing them here though.

**Comment by jviau** [comment]
Tracked by #19
