### ISSUE TITLE
Microsoft.DurableTask.Client.PurgeResult ctor(int) should accept zero

### ISSUE THREAD

**Issue by recumbented** [microsoft/durabletask-dotnet#117]
It can happen no instances purged with PurgeInstancesAsync,
PurgeResult ctor(int) should accept zero.

https://github.com/microsoft/durabletask-dotnet/blob/6bf3bd1268dad704d01f32c375ad2444eec48ac5/src/Client/Core/PurgeResult.cs#L17

**Comment by jviau** [comment]
[v1.0.01](https://www.nuget.org/packages/Microsoft.DurableTask.Client/1.0.1) has been released. You can fix this by pinning the client package in your project:

``` xml
<PackageReference Include="Microsoft.DurableTask.Client" Version="1.0.1" />
```
