### ISSUE TITLE
Retry handlers don't work in Azure Functions

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-dotnet#120]
The discussion [here](https://github.com/Azure/durabletask/pull/853#discussion_r1093578391) made me realize that work hadn't been completed to enable structured error handling in the Azure Functions host. As a result, [this documented sample](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-error-handling?tabs=csharp-isolated#custom-retry-handlers) doesn't work.

Here's a screenshot showing that the exception information was not correctly deserialized by the Durable Task SDK.

![image](https://user-images.githubusercontent.com/2704139/217093804-b5b1bdbd-5bfb-4a6f-b5d1-617ae7a6a003.png)

I suspect the problem was missed because the sidecar we use for integration tests is configured differently from the Azure Functions host.

**Comment by cgillum** [comment]
FYI @kaibocai, we may need to double check this for Java as well.

**Comment by oleks9o6** [comment]
Is there any estimate for the fix? Or, is there a workaround for it?

**Comment by tomseida** [comment]
> * code, `policy.ToDurableTaskCoreRetryOptions()` converts the input into a `DurableTask.Core.RetryOptions`, but doesn't look at the `HandleAsync` at all. My best guess is that it was somehow missed.

Referencing kylepope-ge, is there a fix in the works for missing HandleAsync?

**Comment by violetVo** [comment]
Is there n ETA for the fix?

**Comment by tomseida** [comment]
Can we get an ETA for a fix for this bug. It causes function apps to unnecessarily consume more compute cycles (extra $$$)?

**Comment by alexjamesbrown** [comment]
+1
Is this still the case with Isolated Worker?

**Comment by kylepope-ge** [comment]
Unfortunately, it looks like this still hasn't been fixed. I did a quick check on the latest on the main branch and found the same issues exist with the retry handling. See [TaskOrchestrationContextWrapper.cs:116](https://github.com/microsoft/durabletask-dotnet/blob/c838535adb6aedb6671cf193389ce63a6b4a9b24/src/Worker/Core/Shims/TaskOrchestrationContextWrapper.cs#L116) for the code flow I mentioned back in August.

**Comment by cgillum** [comment]
I'm no longer able to reproduce this. When using the latest release, I'm able to confirm that:

1. The custom retry handler is correctly invoked
2. The error information is correctly surfaced to `retryContext.LastFailure`
