### ISSUE TITLE
Dependency Injection issues are only visible through API/Durable Monitor

### ISSUE THREAD

**Issue by jhueppauff** [microsoft/durabletask-dotnet#123]
Hi, 

I just noticed an issue when using unresolved dependencies within the orchestrator.

When I reference a dependency, which was not injected in the program.cs. The function kick off the orchestrator but no indication is visible, that the dependency could not be loaded and the call is not successful. 
```csharp
private readonly ILogger _logger;
private readonly IService _service;

public FunctionOrchestrator(ILoggerFactory loggerFactory, IService service)
{
        _logger = loggerFactory.CreateLogger<FunctionTrigger>();
        _service = service;
}
[Function(nameof(HelloCitiesUntyped))]
public async Task<string> HelloCitiesUntyped([OrchestrationTrigger] TaskOrchestrationContext context)
{
        string result = "";
	result += await context.CallActivityAsync<string>(nameof(SayHelloUntyped), "Tokyo") + " ";
	result += await context.CallActivityAsync<string>(nameof(SayHelloUntyped), "London") + " ";
	result += await context.CallActivityAsync<string>(nameof(SayHelloUntyped), "Seattle");
	return result;
}

[Function(nameof(SayHelloUntyped))]
public string SayHelloUntyped([ActivityTrigger] string cityName, FunctionContext executionContext)
{
	ILogger logger = executionContext.GetLogger(nameof(SayHelloUntyped));
	logger.LogInformation("Saying hello to {name}", cityName);

	string hello = _service.Hello();

	return $"{hello}, {cityName}!";
}
```
![image](https://user-images.githubusercontent.com/20532954/217512760-ecc9036a-352a-48dc-8f65-f83dd2671d39.png)

Opening the Status Endpoint or the Durable Function Monitor shows exactly the issue: 
![image](https://user-images.githubusercontent.com/20532954/217513089-bce71a96-9252-4c52-b15b-4caddc93ab59.png)

However, with a "normal" Function, whenever there is a dependency which could not be resolved, we get an error message within the console telling the exact problem:
![image](https://user-images.githubusercontent.com/20532954/217512484-291cdaf6-90d1-4756-ab89-305d98365f2c.png)

This behavior is quite frustrating as you can't really tell what the problem is unless you use the Status APIs.

You can find the code I created to reproduce here: 
https://github.com/jhueppauff/DurableFunction-DependencyInjection

**Comment by jviau** [comment]
This happens because the durable functions [middleware](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs#L33) is swallowing that exception so that we can serialize that failure and return it back to the host for persisting in the backend.

We will look into making this a better experience. For now, you can add your own `IFunctionsWorkerMiddleware` that runs _after_ the durable middleware, and catch, log, and rethrow the exception.
