### ISSUE TITLE
Update README with getting started information

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-dotnet#13]
The README should include the following information:

* A link to the Durable Functions documentation
* Code snippets for .NET Isolated
* Notes about source generators
* Information about how this repo relates to the existing GitHub repos (azure/durabletask and azure/azure-functions-durable-extension)
* Standard Microsoft repo README stuff

We can probably avoid talking about the sidecar for now to avoid confusing people.

**Comment by jviau** [comment]
@cgillum I think most of this is covered by the README now. Anything missing or can we close this issue?
