### ISSUE TITLE
Custom telemetry is not being able to sent to azure insights

### ISSUE THREAD

**Issue by serhatataman** [microsoft/durabletask-dotnet#130]
You can see the question I shared here https://stackoverflow.com/questions/75534172/adding-custom-telemetry-to-azure-isolated-worker-process-application-insights and I wonder if there is a limitation in this repository that prevents custom log properties to be sent to azure application insights.

**Comment by jviau** [comment]
@serhatataman I see you added an `ITelemetryInitializer` in your sample code, but I don't see any calls to bootstrap Application Insights SDK in the sample code - which is necessary for AppInsights to function at all. Was that removed for the post, or is it missing?

**Comment by jviau** [comment]
@serhatataman  let me know if more assistance is needed. Closing for now.
