### ISSUE TITLE
Parameters for the orchestration and activities not working correctly

### ISSUE THREAD

**Issue by elias-rod** [microsoft/durabletask-dotnet#133]
Passing parameters to the orchestration or the activities using tuples is supported by the in-process mode, but this durable isolated library is somehow not working with that.

**Repro steps**
1. Download repo https://github.com/elias-rod/Sandbox.git
2. Checkout to branch failing-tuples
3. Go to Function/MyFunctionApp/MyFunctionApp.sln
4. Put breakpoints to validate the value of the parameters is null
5. Execute
6. Go to Function/OldOrchestration/OldOrchestration.sln
7. Put breakpoints to validate the values of the parameters are correct
8. Execute

**Orchestrator parameter failing**
![devenv_aJFGM2GhwZ](https://user-images.githubusercontent.com/12984787/223522349-7dcd0783-5c1e-4d4c-87ed-cecb794395e6.png)

**Activities parameter failing**
![devenv_ZBfXX7LQ6W](https://user-images.githubusercontent.com/12984787/223522192-66971343-1c2b-4b6f-b8a3-0d906c2c6550.png)

**Comment by jviau** [comment]
@elias-rod I theorize this may be the difference in serialization abilities of Newtonsoft.Json vs System.Text.Json. In-Proc uses newtonsoft, which may have serialization support. Isolated uses STJ by default, which may not support value tuple deserialization.

You can easily workaround this by defining your own type. I recommend record structs, they are clean concise:

``` CSharp
public record struct MyInput(string FirstProperty, string SecondProperty);
```

**Comment by jviau** [comment]
@elias-rod found the root issue. See https://github.com/dotnet/runtime/issues/70352

You can work around this by adding this to your `ConfigureServices` in worker startup:

``` CSharp
services.Configure<JsonSerializerOptions>(o => o.IncludeFields = true);
```

However, this might have serious implications on other serialization! I actually **do not** recommend doing this, instead use record structs as I suggested above.

**Comment by jviau** [comment]
Closing as this is external to us - this is System.Text.Json behavior.
