### ISSUE TITLE
Can't pass a big file from an HttpTrigger to an orchestration

### ISSUE THREAD

**Issue by elias-rod** [microsoft/durabletask-dotnet#135]
The user submits an audio file of 20mb for processing, the HttpTrigger function receives the file correctly but on passing the file as byte[] to the orchestration it fails. The in-process Azure Functions support this. The error is:
```
System.Private.CoreLib: Exception while executing function: Functions.HttpTriggerAsync. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode="ResourceExhausted", Detail="Received message larger than max (28014930 vs. 4194304)"))
---> Grpc.Core.RpcException: Status(StatusCode="ResourceExhausted", Detail="Received message larger than max (28014930 vs. 4194304)")
at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.ScheduleNewOrchestrationInstanceAsync(TaskName orchestratorName, Object input, StartOrchestrationOptions options, CancellationToken cancellation)
```

**Comment by jviau** [comment]
This is a limitation of Functions host and gRPC itself - the issue would better be addressed in https://github.com/Azure/azure-functions-dotnet-worker

**Comment by jviau** [comment]
@elias-rod I also do not recommend passing big files to orchestrations. Durable stores all input and output in its own storage, and is constantly serializing / deserializing it. Something of this size is not recommended. It will cause throughput issues, and also even unexpected behavior.

If you need access to this file in activities, I recommend passing the URI of the file and downloading in activities separately.
