### ISSUE TITLE
Exception detail from an activity is lost

### ISSUE THREAD

**Issue by gsimardimt** [microsoft/durabletask-dotnet#140]
How can we return a meaningful exception from an activity? There is a major difference when a System.Exception is thrown from an "in-process" activity versus an "out-of-process" one. 

For instance, based on the "Hello, cities" project, if I do the following:
```
        [Function(nameof(SayHello))]
        public static string SayHello([ActivityTrigger] string name, FunctionContext executionContext)
        {
            if (name.Equals("Seattle"))
                throw new System.Exception($"Could not say hello to {name}.");
                
            ILogger logger = executionContext.GetLogger("SayHello");
            logger.LogInformation("Saying hello to {name}.", name);
            return $"Hello {name}!";
        }
```

The orchestrator function will receive a generic TaskFailedException without any detail and the status query returns the following:

```
{
	"name": "DurableFunctionsOrchestrationCSharp1",
	"instanceId": "784e6bac05ec432d9851bc0a6d5ccdfb",
	"runtimeStatus": "Failed",
	"input": null,
	"customStatus": null,
	"output": "One or more errors occurred. (Task 'SayHello' (#1) failed with an unhandled exception: Exception of type 'DurableTask.Core.Exceptions.TaskFailedException' was thrown.)",
	"createdTime": "2023-03-28T13:09:23Z",
	"lastUpdatedTime": "2023-03-28T13:09:34Z"
}
```

As opposed the following return from an "in-process" activity:

```
{
	"name": "DurableFunctionsOrchestrationCSharp1",
	"instanceId": "e772a93920fe4798bd4aeb5a0337c9e5",
	"runtimeStatus": "Failed",
	"input": null,
	"customStatus": null,
	"output": "Orchestrator function 'DurableFunctionsOrchestrationCSharp1' failed: The activity function 'SayHello' failed: \"Could not say hello to Seattle.\". See the function execution logs for additional details.",
	"createdTime": "2023-03-28T13:03:31Z",
	"lastUpdatedTime": "2023-03-28T13:03:33Z"
}
```

**Comment by cgillum** [comment]
I'm taking a look at this. It seems like there may be a bug where the exception information is not propagating correctly, resulting in the somewhat unhelpful output.

**Comment by jkdmyrs** [comment]
@cgillum I've also noticed a difference with activity failures in regards to Application Insights. 

In the "in-process" model, if an Activity throws an exception that the Orchestration does not handle, both the Activity and Orchestration would be tracked in the "Failures" tab in AI. 

With the "isolated" model, only the failed Activity is tracked in AI. The Orchestration is marked with a `Failed` `RuntimeStatus` in the `...Instances` table in AzureStorage, however, it does not appear in Application Insights as a failure. This seems like a bug to me.

I'm not sure if this is a problem with the DurableTask framework, or Application Insights, so if I need to move this issue to a different repository, please let me know.

**Comment by brrusino** [comment]
@cgillum is there any update on this issue? Have been seeing similar behavior on our end as well.

**Comment by cgillum** [comment]
@gsimardimt or @jkdmyrs, sorry for the really late response. If this issue is still relevant to you, can you tell me more about which [storage backend](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-storage-providers) is your app configured for? We noticed that there are some error propagation behaviors that change depending on which storage backend you're using (for example, the MSSQL backend).

**Comment by gsimardimt** [comment]
I am using the Microsoft SQL Provider.

**Comment by cgillum** [comment]
@gsimardimt thanks for confirming. I think you might be getting impacted by https://github.com/microsoft/durabletask-mssql/issues/161, which is something we plan to work on/fix soon.

**Comment by GOB-Sinzinger** [comment]
Unfortunately, we have run into the same problem.
We use the Azure Storage too.

**Comment by cgillum** [comment]
Thanks @GOB-Sinzinger. We'll take a look.

**Comment by GOB-Sinzinger** [comment]
Thank you @cgillum . Are here any updates on this issue?

We have updated our Azure Function to .NET 8 and the latest Function Framework but are still getting this unhandled exception.

**Comment by cgillum** [comment]
@GOB-Sinzinger would you mind opening a new issue for the problem you're seeing? It seems like there may actually be multiple things discussed in this thread and I want to make sure we cover each issue independently, lest things get lost.

**Comment by cgillum** [comment]
Closing this issue, which was specific to the MSSQL storage provider.
