### ISSUE TITLE
Question: durabletask-dotnet project message

### ISSUE THREAD

**Issue by michaelplavnik** [microsoft/durabletask-dotnet#149]
What is the message of microsoft/durabletask-dotnet project in relation to DTFx. On the surface it is clear “isolated” vs “self-hosted”. But it is not convincing, and I will try to explain.

DTFx architecture is Client programming model (TaskHubClient), Worker programming model (TaskOrchestration<>, TaskActivity<>, OrchestrationContext, ActivityContext, TaskHubWorker), execution engine (TaskHubWorker guts, service abstraction with providers, and middleware). 

Along same lines, durabletask-dotnet architecture is Client programming model, Worker programming model, and execution engine which looks like abstraction not yet born (e.g. GRPC to sidecar with execution by pooling piece of DTFx code, and shims to DTFx). Programming models in durabletask-dotnet has better experience from perspective of modern developer. 

Having two programming models with the same objective does not look sustainable. And this is a real message I hear, and I am trying to get my head around. If durabletask-dotnet is the future (not proven yet, but this might be a long term idea for all I know), then better to build provider abstraction into it and start moving. This will give durabletask a chance to improve some legacy staff in execution abstractions and providers in DTfx without heavy backward compatibility concerns. Especially in areas of event handling, sessions, correlation, resource scheduling (mostly lacking today) and so on.

**Comment by jviau** [comment]
Hi - these are valid points and totally understandable wanting a clear answer for how microsoft/durabletask-dotnet aligns with azure/durabletask. Unfortunately, we are still having internal conversations regarding the long-term vision.

Right now, this repo is primarily used as a programming model for durable functions in dotnet-isolated, as well as dapr workflows. We are still discussing internally what how we envision this repo and azure/durabletask will interact in the long term. You are right there is an opportunity for us to make this into the next evolution of durable-task, and that is something we are contemplating.

**Comment by michaelplavnik** [comment]
Thank you for the extended answer. I am willing to prototype such approach, but I would also like to avoid it to be a waste of effort a-priori. I would appreciate any hint on the matter.
