### ISSUE TITLE
Grpc.Net.Client : "Received message exceeds the maximum configured message size."

### ISSUE THREAD

**Issue by sengiv** [microsoft/durabletask-dotnet#150]
When orchestration `output ` exceeds ~3MB "**message exceeds...**" exception is thrown.
**Is there a way to change the limit?**

Current hack to make work:
![image](https://github.com/Azure/durabletask/assets/43817262/8dbb6080-df4a-48c3-bdef-a89aa4a5664e)
I'm sure there is a better way to do this.

_Running on Azure Functions .NET 7_

**Comment by cgillum** [comment]
I think this is a limitation of the gRPC channel between the durable client and the durable extension running in the host.

We might need to fix this by updating the host to increase the max gRPC message size. Ideally, we could use the same configuration that exists for the Functions host gRPC message size.

Java is likely impacted by this issue as well.

@jviau, would you be able to help with this? Hopefully it's a simple fix?

**Comment by jviau** [comment]
Closing as won't fix as per my comment above.
