### ISSUE TITLE
Documentation for .NET isolated Entity 

### ISSUE THREAD

**Issue by lilyjma** [microsoft/durabletask-dotnet#182]
We need to create similar docs as the following for Entity running in .NET isolated: 

Must have: 
- https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=isolated-process%2Cv3-model%2Cv1-model&pivots=csharp#aggregator
    - Code snippets for aggregator 
- https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=csharp
    - add C# isolated tab in code snippet sections 
- https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities
    - this is a developer guide, we also need migration guide
- https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-isolated-overview#feature-parity-with-in-process-durable-functions
    - remove call out about missing support for Entity 
    - add migration section for Entity
- https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings?tabs=python-v2%2Cin-process%2C2x-durable-functions&pivots=programming-language-csharp#entity-trigger
    - remove call out about missing support for Entity
    - Entity client section may also need updates

Stretch:
- API reference docs like [this](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.extensions.durabletask?view=azure-dotnet)
- https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-serialization-and-persistence?tabs=csharp-isolated#customizing-serialization-and-deserialization
    - (Unsure if this applies to Entity)

**Comment by jviau** [comment]
Docs PR has been merged.
