### ISSUE TITLE
Entities in .NET isolated: Value cannot be null. (Parameter 'input') with Event Hub trigger 

### ISSUE THREAD

**Issue by lilyjma** [microsoft/durabletask-dotnet#223]
Getting "Value cannot be null. (Parameter 'input')" error during runtime with the following: 
```
[Function("EventHubTriggerCSharp")]
public static void Run([EventHubTrigger("jiaymatesthub", Connection = "eh_conn", IsBatched = false)] EventData input,
[DurableClient] DurableTaskClient client)
{
  //some code
}
```
If I remove `[DurableClient] DurableTaskClient client`, then everything works fine. I didn't see this problem with the queue trigger when adding the durable client, so there might be a bug here. 

Here's the full stack trace:

lily@MacBook-Pro AzureFunctionsApp % func start
MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/lily/Desktop/durabletask-dotnet/samples/AzureFunctionsApp/Entities/Counter.cs(125,57): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/lily/Desktop/durabletask-dotnet/samples/AzureFunctionsApp/AzureFunctionsApp.csproj]
  Determining projects to restore...
  Restored /Users/lily/Desktop/durabletask-dotnet/out/samples/obj/AzureFunctionsApp/Debug/net6.0/WorkerExtensions/WorkerExtensions.csproj (in 2.72 sec).
  WorkerExtensions -> /Users/lily/Desktop/durabletask-dotnet/out/samples/obj/AzureFunctionsApp/Debug/net6.0/WorkerExtensions/buildout/Microsoft.Azure.Functions.Worker.Extensions.dll
  AzureFunctionsApp -> /Users/lily/Desktop/durabletask-dotnet/samples/AzureFunctionsApp/bin/output/Samples.AzureFunctionsApp.dll
 
 
Build succeeded.
 
/Users/lily/Desktop/durabletask-dotnet/samples/AzureFunctionsApp/Entities/Counter.cs(125,57): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/lily/Desktop/durabletask-dotnet/samples/AzureFunctionsApp/AzureFunctionsApp.csproj]
    1 Warning(s)
    0 Error(s)
 
Time Elapsed 00:00:07.81
 
 
Azure Functions Core Tools
Core Tools Version:       4.0.5095 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.16.5.20396
 
[2023-10-16T18:59:47.952Z] Found /Users/lily/Desktop/durabletask-dotnet/samples/AzureFunctionsApp/AzureFunctionsApp.csproj. Using for user secrets file configuration.
 
Functions:
 
        AzureFunctionsApp_HttpStart: [GET,POST] http://localhost:7071/api/AzureFunctionsApp_HttpStart
 
        Counter_Add: [POST] [http://localhost:7071/api/counters/{id}/add/{value}](http://localhost:7071/api/counters/%7Bid%7D/add/%7Bvalue%7D)
 
        Counter_Delete: [DELETE] [http://localhost:7071/api/counters/{id}](http://localhost:7071/api/counters/%7Bid%7D)
 
        Counter_Get: [GET] [http://localhost:7071/api/counters/{id}](http://localhost:7071/api/counters/%7Bid%7D)
 
        Counter_Reset: [POST] [http://localhost:7071/api/counters/{id}/reset](http://localhost:7071/api/counters/%7Bid%7D/reset)
 
        DeleteUser: [DELETE] [http://localhost:7071/api/users/{id}](http://localhost:7071/api/users/%7Bid%7D)
 
        Fib: [POST] http://localhost:7071/api/Fib
 
        GetUser: [GET] [http://localhost:7071/api/users/{id}](http://localhost:7071/api/users/%7Bid%7D)
 
        Greeting: [POST] http://localhost:7071/api/Greeting
 
        GreetUser: [POST] [http://localhost:7071/api/users/{id}/greet](http://localhost:7071/api/users/%7Bid%7D/greet)
 
        Lifetime_Delete: [DELETE] [http://localhost:7071/api/lifetimes/{id}](http://localhost:7071/api/lifetimes/%7Bid%7D)
 
        Lifetime_Get: [GET] [http://localhost:7071/api/lifetimes/{id}](http://localhost:7071/api/lifetimes/%7Bid%7D)
 
        Lifetime_Init: [PUT] [http://localhost:7071/api/lifetimes/{id}](http://localhost:7071/api/lifetimes/%7Bid%7D)
 
        PatchUser: [PATCH] [http://localhost:7071/api/users/{id}](http://localhost:7071/api/users/%7Bid%7D)
 
        PutUser: [PUT] [http://localhost:7071/api/users/{id}](http://localhost:7071/api/users/%7Bid%7D)
 
        StartHelloCitiesTyped: [GET,POST] http://localhost:7071/api/StartHelloCitiesTyped
 
        StartHelloCitiesUntyped: [GET,POST] http://localhost:7071/api/StartHelloCitiesUntyped
 
        AzureFunctionsApp: orchestrationTrigger
 
        Counter: entityTrigger
 
        CounterOrchestration: orchestrationTrigger
 
        Counter_Alt: entityTrigger
 
        Counter_State: entityTrigger
 
        FibActivity: activityTrigger
 
        FibOrchestration: orchestrationTrigger
 
        FunctionCounter: entityTrigger
 
        GreetingActivity: activityTrigger
 
        GreetingOrchestration: orchestrationTrigger
 
        HelloCitiesTyped: orchestrationTrigger
 
        HelloCitiesUntyped: orchestrationTrigger
 
        Lifetime: entityTrigger
 
        SayHello: activityTrigger
 
        SayHelloTyped: activityTrigger
 
        SayHelloUntyped: activityTrigger
 
        User: entityTrigger
 
For detailed output, run func with --verbose flag.
[2023-10-16T18:59:53.593Z] Worker process started and initialized.
**[2023-10-16T18:59:53.805Z] The 'EventHubTriggerCSharp' function is in error: Value cannot be null. (Parameter 'input').**
[2023-10-16T18:59:57.611Z] Host lock lease acquired by instance ID '000000000000000000000000DB4F1B81'.

**Comment by jviau** [comment]
@lilyjma I was not able to reproduce this. I was able to connect a EventHub trigger and successfully step into it while also binding the `[DurableClient]`

Can you share your csproj changes?

**Comment by lilyjma** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.0-entities-preview.3" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="5.6.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.0-preview2" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.DurableTask.Generators" Version="1.0.0-preview.1" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>

```

**Comment by lilyjma** [comment]
Closing because this confirmed to be not reproducible.
