### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by zpertee** [microsoft/durabletask-dotnet#233]
Hello.  I apologize for the ignorant question, but can you clarify where orchestration state is being stored?  I would like to utilize something like the [WebAPI sample](https://github.com/microsoft/durabletask-dotnet/tree/main/samples/WebAPI) and would like to understand where the state is being stored and if there is some way that I can layer on the Microsoft.DurableTask.SqlServer package to store state in MSSQL?

**Comment by DL444** [comment]
By default Durable Functions store their execution state in the same Azure Storage Account for your function app as Tables. That's why they recommend that you use General Purpose v1 account for function apps that use durable orchestration - durable orchestration generates a lot of storage transactions, and transaction cost for GPv2 accounts is 10x higher than for GPv1.

It seems that it's possible to store the orchestration state in a SQL Server instance, but evaluate all options first. See the [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-storage-providers) for details.

**Comment by zpertee** [comment]
Thanks.  I've been working extensively with durable functions for a while now, but have recently ran into a bit of a headache.  The back story on my question is that I need to port an Azure hosted Functions web api app to on-premise/offline and add support for self-hosted signlar & durable functions.  The combination of all of these attributes is proving difficult.  To get the self-hosted signalr aspects working I'm thinking that moving to asp.net core is likely the right move.  

I discovered that this repo has an [OrchestrationServiceClientShim](https://github.com/microsoft/durabletask-dotnet/tree/main/src/Client/OrchestrationServiceClientShim) that isn't part of the nuget package that I can use to control where the execution state is saved (_SQL or otherwise_).  Then I might just create a single background worker service, using this [repo](https://github.com/Azure/durabletask) to pull from this storage and run the orchestration jobs.  I would prefer to be able to use the [DurableTaskWorker](https://github.com/microsoft/durabletask-dotnet/blob/main/src/Worker/Core/Hosting/DurableTaskWorker.cs), but outside of GRPC scenarios I'm not sure how this would work exactly.

**Comment by DL444** [comment]
@zpertee I'm definitely not in any position to advise on your migration to on-prem, but if I were you, I'll seriously evaluate migrating to ASP.NET Core, and try to do it if it's not difficult. Yes, you probably can solve all those integration problems you mentioned and host your function apps on premise, but I doubt it would be more straightforward and well-supported than hosting ASP.NET Core.

**Comment by jviau** [comment]
@zpertee this project is not currently intended for non-Durable Functions scenarios. For standalone DurableTask, we still advise you use https://github.com/Azure/durabletask. In which case you will have the option to use `Microsoft.DurableTaskSqlServer` as your backend.

You can also use https://github.com/jviau/durabletask-hosting for dotnet generic host integration with DurableTask.Core.

**Comment by zpertee** [comment]
Thanks.  I'm slowly figuring my way around here and have been able to get most of what I needed.  You guys are doing some really important work and I'm excited to see what comes next.
