### ISSUE TITLE
Where is the "GetInput<T>()" method on TaskActivityContext in Isolated mode?

### ISSUE THREAD

**Issue by Fazer01** [microsoft/durabletask-dotnet#240]
I have created the Durable Functions from the template Visual Studio 2022 provides. Using .NET8 and Isolated mode. 
However, when I want to use `TaskActivityContext` it is saying that `.GetInput<T>()` is available to get the input from the context, but I think it is missing in the implementation. Is this intentional? Is there any other way to get the corresponding orchestration instanceId and the input at the same time?
![Example](https://github.com/microsoft/durabletask-dotnet/assets/37348010/4a86de38-4d2a-4b4c-94e9-dc1e8d1bc0a6)

- Implementation / source in the repository `durabletask-dotnet` the file `src/Abstractions/TaskActivityContext.cs`
![TaskActivityContext.cs](https://github.com/microsoft/durabletask-dotnet/assets/37348010/e2b3fd1d-2930-4ea5-a44d-f7301e344b9b)

When using the InProcess variant, the interface `IDurableActivityContext` is available, where I can access the `InstanceId` property and call the `GetInput<T>()` method to retrieve the input of type T when the activity is called from the orchestrator.

Thanks in advance!

**Comment by jviau** [comment]
Can you share the documentation where it says this is available?

I don't believe we ever added it - for activity input it is expected you bind your input as a parameter:

``` CSHarp
public Task MyActivity([ActivityTrigger] TInput input)
{
}
```

**Comment by Fazer01** [comment]
> Can you share the documentation where it says this is available?
> 
> I don't believe we ever added it - for activity input it is expected you bind your input as a parameter:
> 
> ```cs
> public Task MyActivity([ActivityTrigger] TInput input)
> {
> }
> ```
> 
> I suppose this method leaves you with no access to `InstanceId`, which I assume you want?

That is exactly what I want. Otherwise I have to incorporate the `instanceid` of the calling orchestrator into my `TInput` which is not very neat imho. 

The documentation on the following website states that the former `DurableActivityInput` has no equivalent in the Isolated variant of the Durable Functions Worker. But the docs on the `TaskActivityContext` class states otherwise:

```csharp
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Microsoft.DurableTask;

/// <summary>
/// Defines properties and methods for task activity context objects.
/// </summary>
/// <remarks>
/// A new instance of <see cref="TaskActivityContext"/> is passed as a parameter to each task activity execution. It
/// includes basic information such as the name of the activity, the ID of the invoking orchestration instance, and a
/// method for reading the activity input.
/// </remarks>
public abstract class TaskActivityContext
{
    // IMPORTANT: This abstract class is implemented in the output of source generators, so any changes to the interface
    //            may also need to be reflected in the source generator output.

    /// <summary>
    /// Gets the name of the task activity.
    /// </summary>
    public abstract TaskName Name { get; }

    /// <summary>
    /// Gets the unique ID of the current orchestration instance.
    /// </summary>
    public abstract string InstanceId { get; }
}
```

**Comment by Fazer01** [comment]
> Thanks for the details - we will need to enhance this area for durable functions.

Thanks for adding it as enhancement as this might be a very nice feature to have. Especially because it is available jn the in process mode of the durable functions. 
Any idea when this will become available? Coming months, next year probably?

**Comment by jviau** [comment]
@Fazer01, for getting the parent orchestration id you can add a parameter to your activity function `string instanceId`. This should be bound to the instance ID of the parent orchestration:

``` csharp
[Function(nameof(MyActivity))]
public void MyActivity([ActivityTrigger] MyInput input, string instanceId)
{
}
```

**Comment by Fazer01** [comment]
> @Fazer01, for getting the parent orchestration id you can add a parameter to your activity function `string instanceId`. This should be bound to the instance ID of the parent orchestration:
> 
> ``` csharp
> [Function(nameof(MyActivity))]
> public void MyActivity([ActivityTrigger] MyInput input, string instanceId)
> {
> }
> ```

Tnx! Will have a look into that.
