### ISSUE TITLE
The filter passed to _PurgeAllInstancesAsync(PurgeInstancesFilter filter, CancellationToken cancellation)_ on the DurableTaskClient, is not used, instead a new instance is created

### ISSUE THREAD

**Issue by JohanKlijn** [microsoft/durabletask-dotnet#288]
The filter passed to _PurgeAllInstancesAsync(PurgeInstancesFilter filter, CancellationToken cancellation)_ on the DurableTaskClient, is not used, instead a new instance is created, see https://github.com/microsoft/durabletask-dotnet/blob/main/src/Client/Core/DurableTaskClient.cs#L379C2-L381C88.

Code in DurableTaskClient:
```
    public virtual Task<PurgeResult> PurgeAllInstancesAsync(PurgeInstancesFilter filter, CancellationToken cancellation)
        => this.PurgeAllInstancesAsync(new PurgeInstancesFilter(), null, cancellation);
```

Did not investigate this, but it could be the cause of https://github.com/microsoft/durabletask-dotnet/issues/282

**Comment by jviau** [comment]
Resolved by #289
