### ISSUE TITLE
Activity output serialization uses mix of System.Text.Json and Newtonsoft.Json

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-dotnet#34]
### Issue

When an activity function returns a value, this value is serialized using System.Text.Json. However, when an orchestration attempts to read this value, the reader uses Newtonsoft.Json. This inconsistency makes it possible for an activity to return a value that the orchestration can't read (for example, `JsonElement` objects).

This is also expected to be a problem for sub-orchestration outputs as well as external events.

A fix is needed which replaces the default message serializer used by DurableTask.Core with the data converter used by Microsoft.DurableTask.Client.

**Comment by smokedlinq** [comment]
Stumbled across then when trying to pass around a `Azure.Messaging.CloudEvent` object between orchestrators and activities. I believe this is because the `CloudEvent` is only decorated for `System.Text.Json` converters.

**Comment by jviau** [comment]
I think this can be done without any work on the DurableTask.Core (although it would make it easier). I have accomplished replacing the converter completely in my usage of DTFx. I think I can work up a solution here.

**Comment by saguiitay** [comment]
@cgillum, @jviau - any chance the same issue exists in DurableTask.Core? We're experiencing there something which appears similar.

**Comment by jviau** [comment]
@saguiitay the issue does not exist in Core, at least not by default. Everything is Newtonsoft.Json there by default. But if you do switch out some DataConverters implementations you may get yourself into this state. I have been working on an [extensions package](https://github.com/jviau/durabletask-hosting/blob/main/samples/DurableTask.Extensions.Samples/Program.cs) when I have free time, one of the problems it solves is giving a one-stop solution to replacing the converter in DurableTask.Core. Hopefully I get some time to publish this soon.
