### ISSUE TITLE
Query instance history support

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-dotnet#4]
### Requirement

Orchestration clients should be able to query for an orchestration instance and also get back the history events for that orchestration, similar to the `showHistory` flag mentioned [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#query-instances).

### Implementation notes

The .NET in-process Durable Functions implementation returned a JSON array. For this work-item, we should instead return something structured - e.g., an array of strongly typed objects.

**Comment by jviau** [comment]
I take it this will require a new gRPC message for fetching instance history?

**Comment by cgillum** [comment]
Yes, a new gRPC operation (and corresponding messages) will be required for this. Here is [one example](https://github.com/microsoft/durabletask-java/issues/9) where I go into more details in terms of the steps required for this for Azure Functions (One thing that has changed since I wrote these instructions is that we no longer have the concept of a "sidecar" in DF. Instead, we need to update the GRPC listener in the Durable extension).

**Comment by jviau** [comment]
After some further discussion, we have decided to forgo adding this for now. Instance history is more of an implementation detail, which does not necessarily fit into the .NET SDK or even the gRPC contract. For feature-parity, there will still be the management API in durable functions [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#get-instance-status).
