### ISSUE TITLE
Another preview release?

### ISSUE THREAD

**Issue by BrianVallelunga** [microsoft/durabletask-dotnet#66]
Just curious if another preview release is coming or will it be the final 1.0 version? I'm working on a port of some old webjobs code and am running into some blocking issues (mostly #35).

**Comment by jviau** [comment]
Hi - we are going through some major refactoring right now and will be releasing the next package after that has stabilized a bit.

**Comment by jviau** [comment]
A new preview has been released
https://github.com/microsoft/durabletask-dotnet/releases/tag/v1.0.0-rc.1

**Comment by BrianVallelunga** [comment]
Thank you.
