### ISSUE TITLE
Avoid using input type when using typed functions

### ISSUE THREAD

**Issue by Zerthz** [microsoft/durabletask-dotnet#72]
Is there a good way to not have to use an input type when using the Typed Durable Functions? I want to run a command and have it return. But it doesn't really have to have an input. I know this is a weird question but just checking

**Comment by jviau** [comment]
When you say "Typed Durable Functions", do you mean this: https://github.com/microsoft/durabletask-dotnet/blob/main/samples/AzureFunctionsApp/HelloCitiesTyped.cs#L67?

**Comment by jviau** [comment]
@Zerthz, due to no response in a while I am going to close this issue.

My opinion on the having no-input orchestration is that it is not high priority. It is easy for you to declare it as something trivial like `string?` and then ignore the input in the implementation.
