### ISSUE TITLE
Support for suspend/resume operations

### ISSUE THREAD

**Issue by cgillum** [microsoft/durabletask-dotnet#83]
Here is the feature documentation: https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#suspend-and-resume-instances-preview

Here are the equivalent APIs for the in-proc (WebJobs) model:

* https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableorchestrationclient.suspendasync?view=azure-dotnet#microsoft-azure-webjobs-extensions-durabletask-idurableorchestrationclient-suspendasync(system-string-system-string)
* https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableorchestrationclient.resumeasync?view=azure-dotnet#microsoft-azure-webjobs-extensions-durabletask-idurableorchestrationclient-resumeasync(system-string-system-string)

**Comment by jviau** [comment]
I believe this was added with #97
