### ISSUE TITLE
Allow registering Function classes as services in the container

### ISSUE THREAD

**Issue by julealgon** [microsoft/durabletask-dotnet#88]
While converting my durable function to isolated in .NET7, I ran into a scenario that I'm pretty sure is caused by the fact that function class instances are constructed using something like `ActivatorUtilities.CreateInstance` instead of resolving the type from the container.

I have a simple activity that performs a DELETE Http call to one of my APIs:
```csharp
[DurableTask]
public sealed class DeleteReservationTask : TaskActivityBase<Guid, HttpResponseMessage>
{
    private readonly HttpClient httpClient;

    public DeleteReservationTask(HttpClient httpClient)
        => this.httpClient = httpClient;

    protected override async Task<HttpResponseMessage?> OnRunAsync(TaskActivityContext context, Guid input)
        => await this.httpClient.DeleteAsync($"Reservations/{input}");
}
```

To configure this client, I'm using the `AddHttpClient` method like this:
```csharp
        services
            .AddHttpClient<DeleteReservationTask>()
            .ConfigureHttpClient((provider, client) =>
            {
                var settings = provider.GetRequiredService<IOptions<MyApiSettings>>();
                client.BaseAddress = settings.Value.BaseAddress;
            })
```

When running the integration however, I get a service activation exception:
> [2022-11-25T14:53:24.673Z] System.Private.CoreLib: Exception while executing function: Functions.DeleteReservationTask. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'MyNamespace.DeleteReservationTask'.)

This is happening because `AddHttpClient` registers a named `HttpClient` instance that is resolved only when requesting the service it was registered with. Since the functions runtime is _not_ taking the type from the container, and instead is building it up using ActivatorUtilities, it will ignore that registration and attempt to resolve a "nameless" `HttpClient` from the container when building the type, which will obviously never work.

This makes sense as a default, but I'd like to propose an alternative like the one used by [MVC controllers that provide you with a `AddControllersAsServices()` extension](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.mvccoremvccorebuilderextensions.addcontrollersasservices?view=aspnetcore-7.0) that registers all controllers in the container directly, causing the controller activation logic to request the controller type from the container instead of building the type up manually with `ActivatorUtilities.CreateInstance/CreateFactory`. You could call it `AddFuncitonsAsServices()` or similar, for consistency. Once registered, function classes should then be resolved from the container instead of built-up on the fly, which would then respect whatever registrations are tied to it.

This of course affects other types of patterns other than the typed `HttpClient` registrations. Things such as decorators would also be impossible to register and use today if they target the function class type directly.

Another benefit of something like `AddControllersAsServices` is that it allows the DI container's built-in self-checking mechanism (enabled in debugging by default) to be able to detect missing dependencies before having to run each controller: when they are not registered as services, the container is oblivious to them and cannot perform this check for controller classes. The same benefit would exist for function classes as well.

As for workarounds if anyone is interested, I'll probably just inject the `IHttpClientFactory` and manually fetch the `HttpClient` from it using the class name (which is what happens automatically when the mechanism works as intended). Another workaround of course would be to create an indirection to a second `WhateverService`, that then relies on `HttpClient` and is injected into the function class.

**Comment by jviau** [comment]
@julealgon we now use `ActivatorUtilities.GetServiceOrCreateInstance` when constructing activities, so this should be addressed I believe. Can you see if your scenario now works with `v1.0.0-rc.1` package?

**Comment by julealgon** [comment]
> @julealgon we now use `ActivatorUtilities.GetServiceOrCreateInstance` when constructing activities, so this should be addressed I believe. Can you see if your scenario now works with `v1.0.0-rc.1` package?

@jviau I didn't know this `GetServiceOrCreateInstance` method was introduced, insteresting... since `AddHttpClient` does register the underlying service, it should indeed work.

I'll test and report back.

**Comment by julealgon** [comment]
After updating to `v1.0.0-rc.1`, making the necessary changes (including adding the now separate `.Generators` package), I'm observing the exact same error as before @jviau :

> System.AggregateException: 'One or more errors occurred. (Task 'DeleteReservationTask' (#1) failed with an unhandled exception: One or more errors occurred. (Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'MyCompany.Project.Functions.DeleteReservationTask'.))'

Attempting to explicitly register the function manually also had zero effect.

Are you positive the framework was changed to rely on `GetServiceOrCreateInstance`? If I try to manually call it during startup, it is working just fine for me:

```csharp
var app = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices(
        services => services
            .AddOptions<MyApiSettings>().BindConfiguration(nameof(MyApiSettings)).Services
            .AddHttpClient<DeleteReservationTask>((provider, client) =>
            {
                var settings = provider.GetRequiredService<IOptions<MyApiSettings>>();
                client.BaseAddress = settings.Value.BaseAddress;
            }))
    .Build();

var x = ActivatorUtilities.GetServiceOrCreateInstance<DeleteReservationTask>(app.Services);
```

**Comment by jviau** [comment]
@julealgon I found and fixed the issue for our GA release.

**Comment by julealgon** [comment]
> @julealgon I found and fixed the issue for our GA release.

@jviau while that's pretty cool, I'd not recommend closing this issue quite yet.

One of the main advantages of registering the classes explicitly is that you can leverage the DI container self-checking functionality on those classes too. See my comment from the OP:

> Another benefit of something like `AddControllersAsServices` is that it allows the DI container's built-in self-checking mechanism (enabled in debugging by default) to be able to detect missing dependencies before having to run each controller: when they are not registered as services, the container is oblivious to them and cannot perform this check for controller classes. The same benefit would exist for function classes as well.

Note that one would want this regardless of specific dependencies being injected (so it's not tied to the `HttpClient` scenario I described).

This alone should warrant consideration for a "AddFunctionsAsServices" method that people can opt into using (like `AddControllersAsServices`).

**Comment by jviau** [comment]
@julealgon, the DI validation will be done if you register the tasks to the service container yourself. I am hesitant to add helpers like this as it is extra API surface to maintain which can already be achieved without it. However, if you want to open a new issue specific to that enhancement request ("Add helper to register all tasks in DurableTaskRegistry to IServiceCollection" or something like that), then we can leave it open while we discuss it internally or wait for feedback from others if they also need that functionality. But I would like to elave this issue closed as the original ask is complete - tasks will be resolved from the DI container if they are present.
