### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tomhreb** [microsoft/durabletask-dotnet#91]
Hi,
is there any roadmap or plan when to port Durable Entities and HTTP endpoint calls support?

Thank you

**Comment by jviau** [comment]
Hi @tomhreb,

We don't have a roadmap to share with you right now. Are there any features or issues you are encountering that you would like to see addressed?

**Comment by tomhreb** [comment]
Hi @jviau,
we would like to use azure functions for managing our processes and we liked the idea of automatic snapshotting of api call results. Also, we may have a use case for durable entities, although that's not yet defined.

We would like to host the functions host in AKS. We're okay for now that it's only in preview, as our release date is +- 1 year ahead.

So, if you could share any estimated release date and if/when you are planning to add the api call snapshotting, it would be great.

**Comment by jviau** [comment]
For Durable Entities, we intend to integrate it with the core durable framework and solve some existing issues with it. This will be a considerable amount of work, so it will happen sometime post-GA.

> So, if you could share any estimated release date and if/when you are planning to add the api call snapshotting, it would be great.

We can evaluate bringing this feature over to the out-of-proc model. But you can always write a small activity to call HTTP endpoints, which will accomplish the snapshotting.

**Comment by tomhreb** [comment]
@jviau, ah, right, thanks for the tip and answers.
